export { default as Hero } from './Hero';
export { default as Features } from './Features';
export { default as Reviews } from './Reviews';
export { default as HowItWorks } from './HowItWorks';
export { default as SpecialFeatures } from './SpecialFeatures';
export { default as FinalCTA } from './FinalCTA';
export { default as Footer } from './Footer';
export { default as Demo } from './Demo';
export { default as PersonaProblems } from './PersonaProblems';